main/urls.py

from main import views
from django.urls import path, include


app_name = 'main'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('update_task_info/', views.update_task_info, name='update_task_info'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('task/new/', views.new_task, name='new_task'),
    path('task/edit/<int:task_id>/', views.edit_task, name='edit_task'),
    path('task/delete/<int:task_id>/', views.delete_task, name='delete_task'),
    path('task/<int:task_id>/loop', views.loop_dashboard, name='loop_dashboard'),
    path('loop/new/<int:task_id>', views.new_loop, name='new_loop'),
    path('loop/edit/<int:task_id>/<int:loop_id>/',
         views.edit_loop, name='edit_loop'),
    path('loop/delete/<int:loop_id>/', views.delete_loop, name='delete_loop'),
    path('task/result/<int:task_id>/',
         views.get_result, name='get_result'),
    path('task/result/download/file/<int:result_id>',
         views.download_file, name='download_file'),
    path('task/result/download/video/<int:task_id>',
         views.download_video, name='download_video'),
    path('task/result/download/file/all/<int:task_id>',
         views.download_all_file, name='download_all_file'),
    path('task/result/download/file/raw/<int:task_id>',
         views.download_raw_file, name='download_raw_file'),
    path('detection/<int:task_id>/', views.call_detect, name='call_detect'),
    path('login', views.login_view, name='login'),
    path('signup', views.signup_view, name='signup'),
    path('logout', views.logout_view, name='logout'),
    path('home', views.home_page, name='home'),
    path('account', views.account_page, name='account_page'),
    path('search/', views.search, name='search'),
    path('notifications/', views.notifications, name='notifications'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('main/', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils import timezone
from django_celery_results.models import TaskResult
# Create your models here.
from django.core.validators import FileExtensionValidator


class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    task_id_celery = models.CharField(max_length=50, null=True)
    date_time = models.CharField(max_length=50)
    time = models.CharField(max_length=50)
    date_time_modify = models.DateTimeField(auto_now=True)
    date_time_upload = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    longtitude = models.CharField(max_length=50)
    latitude = models.CharField(max_length=50)
    video_file = models.FileField(
        upload_to='videos/', validators=[FileExtensionValidator(['mp4', 'avi', 'mov'])])
    video_result_file = models.FileField(upload_to='result/video/', null=True, validators=[
                                         FileExtensionValidator(['mp4', 'avi', 'mov'])])
    counting_result_file = models.FileField(
        upload_to='result/counting/', null=True)
    image_file = models.ImageField(upload_to='images/', validators=[
                                   FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], null=True)


class LoopResult(models.Model):
    task_loop_result = models.ForeignKey(
        Task, on_delete=models.CASCADE)
    loop_id = models.IntegerField()
    summary_file = models.FileField(
        upload_to='result/summary/', null=True)


class VehicleCount(models.Model):
    loop_result = models.ForeignKey(
        LoopResult, on_delete=models.CASCADE)
    loop_id = models.IntegerField()
    vehicle_type = models.CharField(max_length=50)
    entered = models.IntegerField()
    straight = models.IntegerField()
    right = models.IntegerField()
    left = models.IntegerField()


class Loop(models.Model):
    ORIENTATION = [
        ("COUNTERCLOCKWISE", "counterclockwise"),
        ("CLOCKWISE", "clockwise"),
    ]
    head_task = models.ForeignKey(Task, on_delete=models.CASCADE)
    loop_name = models.CharField(max_length=255)
    loop_id = models.IntegerField()
    x_1 = models.IntegerField()
    y_1 = models.IntegerField()
    x_2 = models.IntegerField()
    y_2 = models.IntegerField()
    x_3 = models.IntegerField()
    y_3 = models.IntegerField()
    x_4 = models.IntegerField()
    y_4 = models.IntegerField()
    orientation = models.CharField(max_length=20, choices=ORIENTATION)
    summary_location_x = models.IntegerField()
    summary_location_y = models.IntegerField()

    def __str__(self):
        return self.loop_name

main/forms.py
from django import forms
from .models import Task, Loop
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import DateTimeInput, TimeInput
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['date_time', 'time', 'location', 'description', 'latitude', 'longtitude',
                  'video_file',]
        widgets = {
            'date_time': DateTimeInput(attrs={'type': 'date'}),
            'time': TimeInput(attrs={'type': 'time'}),
        }

    def clean_video_file(self):
        video_file = self.cleaned_data.get('video_file')
        if video_file:
            if not video_file.name.endswith('.mp4'):
                raise ValidationError('Only MP4 files are allowed.')
        return video_file


class LoopForm(forms.ModelForm):

    # loop_id = forms.IntegerField(validators=[MinValueValidator(0)])
    x_1 = forms.DecimalField(validators=[MinValueValidator(0)], initial=900)
    y_1 = forms.DecimalField(validators=[MinValueValidator(0)], initial=600)
    x_2 = forms.DecimalField(validators=[MinValueValidator(0)], initial=900)
    y_2 = forms.DecimalField(validators=[MinValueValidator(0)], initial=300)
    x_3 = forms.DecimalField(validators=[MinValueValidator(0)], initial=400)
    y_3 = forms.DecimalField(validators=[MinValueValidator(0)], initial=300)
    x_4 = forms.DecimalField(validators=[MinValueValidator(0)], initial=400)
    y_4 = forms.DecimalField(validators=[MinValueValidator(0)], initial=600)
    summary_location_x = forms.DecimalField(
        validators=[MinValueValidator(0)], initial=20)
    summary_location_y = forms.DecimalField(
        validators=[MinValueValidator(0)], initial=20)

    class Meta:
        model = Loop
        fields = ['loop_name', 'x_1', 'y_1', 'x_2', 'y_2', 'x_3', 'y_3', 'x_4', 'y_4', 'orientation',
                  'summary_location_x', 'summary_location_y']


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

main/views.py
# from django.shortcuts import render
import matplotlib.pyplot as plt
import matplotlib
from django.http import JsonResponse
from mysite.tasks import *
import json
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from .models import Task, Loop, LoopResult, VehicleCount
from .forms import TaskForm, LoopForm
from django.core.files.base import ContentFile
import os
from django_celery_results.models import TaskResult
from celery.result import AsyncResult
from datetime import datetime
from django.http import FileResponse
from django.shortcuts import get_object_or_404
import os
import zipfile
from django.http import HttpResponse
import io
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import imageio.v3 as iio
from django.conf import settings
from PIL import Image, ImageDraw
import base64
from io import BytesIO
import cv2
import numpy as np
media_url = settings.MEDIA_URL
matplotlib.use('Agg')


def preview_loop_image(task, loops, task_id):
    image_path = task.image_file
    image = Image.open(image_path)

    # Draw a box on the image if there are loops
    if loops:
        loopfile = loops_to_json(task_id)
        img_array = np.array(image)
        image_draw = draw_loops_test(img_array, loopfile)
        image = Image.fromarray(image_draw)

    # Set figure size
    fig = plt.figure(figsize=(10, 10))

    # Plot the image with aspect ratio set to 'equal'
    plt.imshow(np.array(image), aspect='equal')

    # Set x and y axis scales
    plt.xticks(ticks=range(0, image.size[0], 100))
    plt.yticks(ticks=range(0, image.size[1], 100))

    # Set x and y axis labels
    plt.xlabel('X Scale')
    plt.ylabel('Y Scale')

    # Save the plot to a buffer
    buf = io.BytesIO()
    plt.savefig(buf, format='png', bbox_inches='tight')
    buf.seek(0)

    # Convert the buffer to a base64-encoded string
    encoded_image = base64.b64encode(buf.getvalue()).decode('utf-8')

    return encoded_image


def draw_loops_test(img, loopfile):
    count_boxes = loopfile
    loops = count_boxes["loops"]
    for loop in loops:
        pt0, pt1, pt2, pt3 = loop["points"]

        cv2.line(img, (pt0["x"], pt0["y"]), (pt1["x"],
                 pt1["y"]), (255, 0, 0), 2)  # entering line
        cv2.line(img, (pt1["x"], pt1["y"]), (pt2["x"],
                 pt2["y"]), (255, 255, 0), 2)  # left line
        cv2.line(img, (pt2["x"], pt2["y"]), (pt3["x"],
                 pt3["y"]), (255, 255, 0), 2)  # straight
        cv2.line(img, (pt3["x"], pt3["y"]), (pt0["x"],
                 pt0["y"]), (255, 255, 0), 2)  # right
        cv2.putText(img, loop["name"], (pt0["x"], pt0["y"]),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, [0, 255, 0], 2)

    return (img)


def new_loop(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    loops = Loop.objects.filter(head_task__pk=task_id)
    loop_count = Loop.objects.filter(head_task=task).count()
    if request.method == 'POST':
        form = LoopForm(request.POST)
        if form.is_valid():
            loop = form.save(commit=False)
            loop.loop_id = loop_count
            loop.head_task = task
            loop.save()
            return redirect(reverse("main:loop_dashboard", args=(task_id,)))
    else:
        form = LoopForm(initial={'head_task': task})

    encoded_image = preview_loop_image(task, loops, task_id)

    return render(request, 'loop/NewLoop.html', {'form': form, 'task_id': task_id, 'encoded_image': encoded_image})


def edit_loop(request, loop_id, task_id):
    loop = get_object_or_404(Loop, pk=loop_id)
    task = Task.objects.get(pk=task_id)

    encoded_image = preview_loop_image(task, loop, task_id)

    if request.method == 'POST':
        form = LoopForm(request.POST, instance=loop)
        if form.is_valid():
            form.save()
            return redirect(reverse("main:loop_dashboard", args=(loop.head_task.pk,)))
    else:
        form = LoopForm(instance=loop)
    return render(request, 'loop/EditLoop.html', {'form': form, 'task_id': loop.head_task.pk, 'encoded_image': encoded_image})


def loop_dashboard(request, task_id):
    loops = Loop.objects.filter(head_task__pk=task_id)
    task = Task.objects.get(pk=task_id)

    encoded_image = preview_loop_image(task, loops, task_id)

    return render(request, 'loop/LoopDashboard.html', {'loops': loops, 'task_id': task_id, 'task': task, 'encoded_image': encoded_image})


def new_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES)
        if form.is_valid():
            task = form.save(commit=False)
            task.save()

            video_file = task.video_file.path
            folder_path = os.path.join(settings.MEDIA_ROOT, 'result/images')
            if not os.path.exists(folder_path):
                os.makedirs(folder_path)
            img_path = os.path.join(
                settings.MEDIA_ROOT, 'result', 'images', f"{task.task_id}.png")

            for frame_count, frame in enumerate(iio.imiter(video_file)):
                iio.imwrite(img_path, frame, format='png')
                if frame_count == 0:
                    break

            # save the image file path in the database
            task.image_file = img_path
            task.save()

            return redirect(reverse("main:dashboard"))
    else:
        form = TaskForm()
    return render(request, 'task/NewTask.html', {'form': form})


def signup_view(request):
    if (request.user.is_authenticated):
        return redirect('main:home')
    else:
        form = CreateUserForm()
        if (request.method == 'POST'):
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(
                    request, 'Successful you can login as username: ' + user)
                return redirect('main:login')

        context = {'form': form}
        return render(request, 'authenticate/signup.html', context)


def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return render(request, 'authenticate/home.html')
        else:
            messages.info(request, "Username or Password is incorrect.")
    return render(request, 'authenticate/login.html')


def logout_view(request):
    logout(request)
    return redirect('main:login')


def home_page(request):
    return render(request, 'authenticate/home.html')


def account_page(request):
    username = request.user.username
    context = {'name': username}
    return render(request, 'authenticate/account.html', context)


def download_file(request, result_id):
    obj = get_object_or_404(LoopResult, pk=result_id)
    file = obj.summary_file.open('rb')
    response = FileResponse(file)
    response.content_type = 'text/csv'
    task_id = obj.task_loop_result.task_id
    loop_id = obj.loop_id
    response['Content-Disposition'] = f'attachment; filename="{task_id}_{loop_id}.csv"'

    return response


def download_raw_file(request, task_id):
    obj = get_object_or_404(Task, task_id=task_id)
    file = obj.counting_result_file.open('rb')
    response = FileResponse(file)
    response.content_type = 'text/csv'
    response['Content-Disposition'] = f'attachment; filename="{obj.task_id}.txt"'
    return response


def download_video(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    video_path = task.video_result_file.path
    filename = task.video_file.name.split('/')[-1]
    response = FileResponse(open(video_path, 'rb'), content_type='video/mp4')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    return response


def download_all_file(request, task_id):
    directory_path = f"media/result/summary/{task_id}/"

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as zip_file:
        for file_name in os.listdir(directory_path):
            file_path = os.path.join(directory_path, file_name)
            if os.path.isfile(file_path):
                zip_file.write(file_path, file_name)

    zip_file_name = f"{task_id}.zip"

    response = HttpResponse(buffer.getvalue(), content_type="application/zip")
    response["Content-Disposition"] = f"attachment; filename={zip_file_name}"

    return response


def dashboard(request):
    tasks = Task.objects.all()
    task_status_data = []
    for task in tasks:
        if task.task_id_celery is not None:
            task_result = AsyncResult(task.task_id_celery)
            status = task_result.status
        else:
            status = "UNPROCESS"
        task_status_data.append({
            'task_id': task.task_id,
            'location': task.location,
            'description': task.description,
            'date_time': task.date_time,
            'status': status,
            'time': task.time,
        })
    return render(request, 'task/Dashboard.html', {'tasks': task_status_data})


def update_task_info(request):
    tasks = Task.objects.all()
    task_status_data = []
    for task in tasks:
        if task.task_id_celery is not None:
            task_result = AsyncResult(task.task_id_celery)
            status = task_result.status

main/templates/loop/EditLoop.html
{% extends 'base.html' %}

{% block content %}
<style>

    h1{
      text-align: center;
    }

    .new-loop-form button[type=submit]{
        display: inline-block;
        background-color: #44df1c;
        color: white;
        padding: 3px 8px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
        margin-left: 20%;
    }
    
    .image-container {
        margin-left: 20%;
        margin-right: auto;
    }
    

</style>
<section class="new-loop-form" >
    <h1>Edit Loop</h1>
    <div class="image-container">
        <img src="data:image/jpeg;base64,{{ encoded_image }}" alt="Modified Image" style="max-width: 70%; height: auto;">
    </div>
    <div class="form-loop">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} 
            {{ form.as_p }}
            <button type="submit">Save</button>
            <a class="btn btn-back-loop new-loop-back" href="{% url 'main:loop_dashboard' task_id %}">back</a>
        </form>
    </div>
</section>

{% endblock %}

main/templates/loop/LoopDashboard.html

{% extends 'base.html' %}

{% block content %}
<style>

    th{
        text-align: center;
    }

    .video-section{
            display: flex;
            flex-direction: row;
            flex-wrap: nowrap;
        }

    .video-edit{
            margin-left: 25%;
            margin-right: 5%;
        }

    .btn-new-loop{
            margin-left: 70%;
            margin-top: 2%;
            margin-bottom: 2%;
            background-color: grey;
            border-color: grey;
        }

    .table-editloop{
        text-align: center;
        margin-right: 25%;
        margin-left: 1%;

    }

    .btn-create{
        color: white;
        background-color: #dc3545;
        border: none;
    }

    .btn-create:hover {
        text-decoration: none;
        color: black;
        background-color: #dc3545;
    }

    .btn-back-loop{
        margin-left: 73%;
        margin-right: auto;
        color: white;
        background-color: #ffc107;
        border: none;
    }

    .btn-warning{
        color: white;
        background-color: #ffc107;
        border: none;
    }

    .btn-danger{
        background-color: #dc3545;
        color: white;
    }

    .image-container {
        display: flex;
        justify-content: flex-end;
    }

</style>
<h1 class="loop-header">Loop Dashboard</h1>
<a href="{% url 'main:new_loop' task_id %}" class="btn btn-success btn-create btn-new-loop">+  New Loop</a>
<br>
{% load static %}

<div class="video-section">
    <div class="image-container">
        <img src="data:image/jpeg;base64,{{ encoded_image }}" alt="Modified Image" style="max-width: 50%; height: auto;">
    </div>
    <div class="table-editloop">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Loop ID</th>
                <th scope="col">Loop Name</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for loop in loops %}
            <tr>
                <td>{{ loop.loop_id }}</td>
                <td>{{ loop.loop_name }}</td>
                <td><a class="btn btn-warning" href="{% url 'main:edit_loop' task_id loop.pk %}" role="button">Edit</a>
                <td><a class="btn btn-danger" href="{% url 'main:delete_loop' loop.pk %}" role="button">Delete</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div> 
<a class="btn btn-back-loop back-btn" href="{% url 'main:dashboard'  %}">back</a>
{% endblock %}

main/templates/loop/NewLoop.html
{% extends 'base.html' %}

{% block content %}
<style>
    h1{
        text-align: center;
    }

    .new-loop-form button[type=submit]{
        display: inline-block;
        background-color: #44df1c;
        color: white;
        padding: 3px 8px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
        margin-left: 20%;
    }

    .image-container {
        margin-left: 20%;
        margin-right: auto;
    }

</style>
<section class="new-loop-form" >
    <h1 style="text-align: center;">New Loop</h1>
    <h2 style="text-align: center;">Information</h2>
    <div class="image-container">
        <img src="data:image/jpeg;base64,{{ encoded_image }}" alt="Modified Image" style="max-width: 70%; height: auto;">
    </div>
    <div class="form-loop">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}   
            <button type="submit">New Loop</button>
            <a class="btn btn-back-loop new-loop-back" href="{% url 'main:loop_dashboard' task_id %}">back</a>
        </form>
    </div>
</section>
{% endblock %}